defaultEntryPoints = ["http", "https"]

[log]
  level = "INFO"

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"
  [entryPoints.traefik]
    address = ":8082"

[retry]

[api]
  dashboard = true
  insecure = true

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false

#[certificatesresolvers.myhttpchallenge.acme]
#  email = "robin.mercier@epitech.eu"
#  storage = "/letsencrypt/acme.json"
#  [certificatesresolvers.myhttpchallenge.acme.httpChallenge]
#    entryPoint = "http"
